#!/bin/bash

echo "=== Unified Workflow Go - Postman/Curl Test Commands ==="
echo "All services must be running: docker-compose up -d"
echo ""

echo "## 1. HEALTH CHECKS"
echo ""

echo "# Registry Service Health"
echo "curl -X GET http://localhost:8080/health"
echo "curl -X GET http://localhost:8080/health | jq ."
echo ""

echo "# Executor Service Health"
echo "curl -X GET http://localhost:8081/health"
echo "curl -X GET http://localhost:8081/health | jq ."
echo ""

echo "# Executor DI Framework Health"
echo "curl -X GET http://localhost:8081/health/di"
echo "curl -X GET http://localhost:8081/health/di | jq ."
echo ""

echo "## 2. REGISTRY SERVICE ENDPOINTS"
echo ""

echo "# List all workflows (GET)"
echo "curl -X GET http://localhost:8080/api/v1/workflows"
echo "curl -X GET http://localhost:8080/api/v1/workflows | jq ."
echo ""

echo "# Create a workflow (POST)"
echo "curl -X POST http://localhost:8080/api/v1/workflows \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"name\":\"Test Workflow\",\"description\":\"A test workflow with steps\",\"steps\":[{\"type\":\"echo\",\"name\":\"echo-step-1\",\"config\":{\"message\":\"Hello World\"}},{\"type\":\"sequential\",\"name\":\"seq-step-1\"}]}'"
echo ""

echo "# Create a simple workflow without steps (POST)"
echo "curl -X POST http://localhost:8080/api/v1/workflows \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"name\":\"Simple Workflow\",\"description\":\"A simple workflow without steps\"}'"
echo ""

echo "# Get workflow by ID (GET)"
echo "# Replace {workflow_id} with actual ID from create response"
echo "curl -X GET http://localhost:8080/api/v1/workflows/{workflow_id}"
echo "curl -X GET http://localhost:8080/api/v1/workflows/{workflow_id} | jq ."
echo ""

echo "# Check if workflow exists (GET)"
echo "curl -X GET http://localhost:8080/api/v1/workflows/{workflow_id}/exists"
echo "curl -X GET http://localhost:8080/api/v1/workflows/{workflow_id}/exists | jq ."
echo ""

echo "# Get workflow count (GET)"
echo "curl -X GET http://localhost:8080/api/v1/workflows/count"
echo "curl -X GET http://localhost:8080/api/v1/workflows/count | jq ."
echo ""

echo "# Update workflow (PUT) - Note: Implementation pending"
echo "curl -X PUT http://localhost:8080/api/v1/workflows/{workflow_id} \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"name\":\"Updated Workflow Name\",\"description\":\"Updated description\"}'"
echo ""

echo "# Delete workflow (DELETE)"
echo "curl -X DELETE http://localhost:8080/api/v1/workflows/{workflow_id}"
echo "curl -X DELETE http://localhost:8080/api/v1/workflows/{workflow_id} | jq ."
echo ""

echo "## 3. EXECUTOR SERVICE ENDPOINTS"
echo ""

echo "# Execute workflow by ID (POST)"
echo "# Note: This may fail if executor can't find workflow in registry"
echo "curl -X POST http://localhost:8081/api/v1/execute \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"workflow_id\":\"{workflow_id}\",\"input_data\":{\"test\":\"data\",\"value\":123}}'"
echo ""

echo "# Get execution status (GET)"
echo "# Replace {run_id} with ID from execute response"
echo "curl -X GET http://localhost:8081/api/v1/execute/{run_id}/status"
echo "curl -X GET http://localhost:8081/api/v1/execute/{run_id}/status | jq ."
echo ""

echo "# Get execution data (GET)"
echo "curl -X GET http://localhost:8081/api/v1/execute/{run_id}/data"
echo "curl -X GET http://localhost:8081/api/v1/execute/{run_id}/data | jq ."
echo ""

echo "# List executions (GET)"
echo "curl -X GET http://localhost:8081/api/v1/execute"
echo "curl -X GET http://localhost:8081/api/v1/execute | jq ."
echo ""

echo "# Cancel execution (POST)"
echo "curl -X POST http://localhost:8081/api/v1/execute/{run_id}/cancel"
echo "curl -X POST http://localhost:8081/api/v1/execute/{run_id}/cancel | jq ."
echo ""

echo "# Pause execution (POST)"
echo "curl -X POST http://localhost:8081/api/v1/execute/{run_id}/pause"
echo "curl -X POST http://localhost:8081/api/v1/execute/{run_id}/pause | jq ."
echo ""

echo "# Resume execution (POST)"
echo "curl -X POST http://localhost:8081/api/v1/execute/{run_id}/resume"
echo "curl -X POST http://localhost:8081/api/v1/execute/{run_id}/resume | jq ."
echo ""

echo "# Retry execution (POST)"
echo "curl -X POST http://localhost:8081/api/v1/execute/{run_id}/retry"
echo "curl -X POST http://localhost:8081/api/v1/execute/{run_id}/retry | jq ."
echo ""

echo "# Get execution metrics (GET)"
echo "curl -X GET http://localhost:8081/api/v1/execute/{run_id}/metrics"
echo "curl -X GET http://localhost:8081/api/v1/execute/{run_id}/metrics | jq ."
echo ""

echo "## 4. DI FRAMEWORK ENDPOINTS"
echo ""

echo "# Get DI container health (GET)"
echo "curl -X GET http://localhost:8081/health/di/components"
echo "curl -X GET http://localhost:8081/health/di/components | jq ."
echo ""

echo "# Get DI container metrics (GET)"
echo "curl -X GET http://localhost:8081/health/di/metrics"
echo "curl -X GET http://localhost:8081/health/di/metrics | jq ."
echo ""

echo "## 5. WORKER SERVICE (No direct HTTP endpoints - processes messages from NATS)"
echo ""

echo "# Check worker logs"
echo "docker-compose logs worker-service"
echo ""

echo "## 6. NATS MESSAGE QUEUE"
echo ""

echo "# Check NATS monitoring (if accessible)"
echo "curl -X GET http://localhost:8222/"
echo ""

echo "## 7. COMPREHENSIVE TEST SCRIPT"
echo ""
echo "Here's a complete test script you can run:"
echo ""
echo "#!/bin/bash"
echo "echo '=== Starting Comprehensive Test ==='"
echo ""
echo "# 1. Check health"
echo "echo '1. Checking service health...'"
echo "curl -s http://localhost:8080/health | jq -r '.status'"
echo "curl -s http://localhost:8081/health | jq -r '.status'"
echo ""
echo "# 2. Create a workflow"
echo "echo '2. Creating test workflow...'"
echo "WORKFLOW_RESPONSE=\$(curl -s -X POST http://localhost:8080/api/v1/workflows \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"name\":\"Postman Test Workflow\",\"description\":\"Workflow for Postman testing\",\"steps\":[{\"type\":\"echo\",\"name\":\"test-echo\",\"config\":{\"message\":\"Test\"}}]}')"
echo "WORKFLOW_ID=\$(echo \$WORKFLOW_RESPONSE | jq -r '.id')"
echo "echo \"Created workflow ID: \$WORKFLOW_ID\""
echo ""
echo "# 3. Get workflow details"
echo "echo '3. Getting workflow details...'"
echo "curl -s http://localhost:8080/api/v1/workflows/\$WORKFLOW_ID | jq ."
echo ""
echo "# 4. List all workflows"
echo "echo '4. Listing all workflows...'"
echo "curl -s http://localhost:8080/api/v1/workflows | jq '.total_count'"
echo ""
echo "# 5. Try to execute workflow"
echo "echo '5. Attempting to execute workflow...'"
echo "EXECUTE_RESPONSE=\$(curl -s -X POST http://localhost:8081/api/v1/execute \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d \"{\\\"workflow_id\\\":\\\"\$WORKFLOW_ID\\\",\\\"input_data\\\":{\\\"test\\\":\\\"value\\\"}}\")"
echo "echo \"Execute response: \$EXECUTE_RESPONSE\""
echo ""
echo "# 6. Check DI framework health"
echo "echo '6. Checking DI framework health...'"
echo "curl -s http://localhost:8081/health/di | jq '.health | length'"
echo ""
echo "echo '=== Test Complete ==='"
echo ""
echo "## 8. TROUBLESHOOTING"
echo ""
echo "# If executor can't find workflow:"
echo "# 1. Check if registry and executor are in same Docker network"
echo "# 2. Check if executor can reach registry internally:"
echo "docker-compose exec executor-service wget -q -O- http://registry-service:8080/health"
echo ""
echo "# If services are not running:"
echo "docker-compose up -d"
echo ""
echo "# To rebuild and restart services:"
echo "docker-compose build"
echo "docker-compose up -d"
echo ""
echo "# To view logs:"
echo "docker-compose logs -f registry-service"
echo "docker-compose logs -f executor-service"
echo "docker-compose logs -f worker-service"
echo ""
echo "## 9. IMPORTANT NOTES"
echo ""
echo "1. Registry Service: Port 8080"
echo "2. Executor Service: Port 8081"
echo "3. Worker Service: No HTTP port (processes NATS messages)"
echo "4. NATS: Port 4222 (messaging), 8222 (monitoring)"
echo "5. Workflow steps are now properly stored in registry (bug fixed)"
echo "6. Executor may have issues finding workflows from registry (known issue)"
echo "7. DI framework shows 11 healthy components when working"
echo ""
echo "Use these commands in Postman by:"
echo "1. Create a new collection 'Unified Workflow Go'"
echo "2. Add environment variables: base_url_registry=http://localhost:8080, base_url_executor=http://localhost:8081"
echo "3. Create requests using the curl commands above"
echo "4. Use tests to extract workflow_id and run_id from responses for subsequent requests"
